### ISSUE TITLE
hecl crashes on extraction

### ISSUE THREAD

**Issue by hikagura99** [AxioDL/metaforce#450]
The error
```

Metroid3.pak             DCLN_29280F1C   2% [-------------------------------]
[36.6345 ERROR hecl::blender::Connection (HECL Worker 0)] Pipe error 0 No such file or directory
[36.7348 FATAL ERROR hecl::blender::Connection (HECL Worker 0)] 
Traceback (most recent call last):
  File "/tmp/hecl_blendershell.py", line 485, in <module>
    bpy.ops.file.hecl_patching_load()
  [36.6345 ERROR hecl::blender::Connection (HECL Worker 0)] Pipe error 0 No such file or directory
[36.7348 FATAL ERROR hecl::blender::Connection (HECL Worker 0)] 
Traceback (most recent call last):
  File "/tmp/hecl_blendershell.py", line 485, in <module>
    bpy.ops.file.hecl_patching_load()
  File "/usr/share/blender/3.1/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.file.hecl_patching_load" error, could not be found
```
Artix Linux
Kernel 5.17.1-zen1-1-zen
CPU Intel i5 7200u 3.10 GHz dual core
RAM 8GB
Blender version 17:3.1.2-1
Latest pull of the git, all submodules updated
Metroid Prime Gamecube PAL Version

**Comment by hikagura99** [comment]
my bad just had to open blender for the first time
P.S. please write it on the dependency list
